### ISSUE TITLE
Number of features does not match the number of nodes when num_heads > 1

### ISSUE THREAD

**Issue by Jonbroad15** [tech-srl/how_attentive_are_gats#2]
Hi, I am using the DGL based code of the project. When I set `num_heads = 2` to initialize the GATv2Conv layers I receive the following error 

`dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 568 and 284 instead`

I guess the attention heads are not being aggregated? I noticed the DGL version does not have an `is_concat` option like in the [annotated code demo](https://nn.labml.ai/graphs/gatv2/)

**Comment by shakedbr** [comment]
Hi @Jonbroad15,
The proteins script is working with dgl==0.6.0.
I suggest trying to use the [GATv2 implementation](https://docs.dgl.ai/generated/dgl.nn.pytorch.conv.GATv2Conv.html#dgl.nn.pytorch.conv.GATv2Conv) in the DGL package which is actively maintained.
Regarding the concatenation, in the DGL layer, the return value is a tensor of shape `(N, H, D)` where `H` is the number of heads, and `D` is the size of output feature. Therefore,  you can take this output and use concatenation or some pooling.

**Comment by shakedbr** [comment]
Hi @Jonbroad15,
I'm closing this issue.
If you still have any problems, please reopen this issue.
