### ISSUE TITLE
(Possible) bug when graph.is_block is True

### ISSUE THREAD

**Issue by adrianjav** [tech-srl/how_attentive_are_gats#4]
Sorry for bothering again.

This might be dumb, but I am reading the DGL implementation to understand it, and I really don't get L272.

https://github.com/tech-srl/how_attentive_are_gats/blob/b5ccb6129878bb6f6f8c3f77934046d8e0920a52/gatv2_conv_DGL.py#L266-L272

The only thing that makes sense to me is that the rhs was supposed to be `feat_dst` as well, and this is some bug. Otherwise, it does not make sense to set `share_weights=False` when `graph.is_block` is True. Am I missing something?

**Comment by shakedbr** [comment]
Thanks for pointing this out.
We created this GATv2 module by adapting the DGL's GAT module, and since we didn't use block graphs in our experiments, we haven't noticed this issue.

Following GAT implementation, The correct L271-L272 should be
```diff
- feat_dst = feat_src[:graph.number_of_dst_nodes()] 
+ feat_dst = feat_dst[:graph.number_of_dst_nodes()] 
+ h_dst = h_dst[:graph.number_of_dst_nodes()]
```

What do you think?

**Comment by adrianjav** [comment]
That looks good to me 👍🏼

**Comment by shakedbr** [comment]
Hi @adrianjav,
I'm closing this issue.
If you still have any problems, please reopen this issue.
